src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $roles;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Location;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $School;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Department;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $website;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $info;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $skills;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fax;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email2;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $workarea;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $titleandtasks;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $edulis;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $edumaster;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $edudoc;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $thesismaster;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $thesisdoc;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $roomno;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $notification;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles= explode(',',$this->roles);
        return array_unique($roles);
    }

    public function setRoles(string $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = password_hash($password,PASSWORD_BCRYPT);

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->Location;
    }

    public function setLocation(?string $Location): self
    {
        $this->Location = $Location;

        return $this;
    }

    public function getSchool(): ?string
    {
        return $this->School;
    }

    public function setSchool(?string $School): self
    {
        $this->School = $School;

        return $this;
    }

    public function getDepartment(): ?string
    {
        return $this->Department;
    }

    public function setDepartment(?string $Department): self
    {
        $this->Department = $Department;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getInfo(): ?string
    {
        return $this->info;
    }

    public function setInfo(?string $info): self
    {
        $this->info = $info;

        return $this;
    }

    public function getSkills(): ?string
    {
        return $this->skills;
    }

    public function setSkills(?string $skills): self
    {
        $this->skills = $skills;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getFax(): ?string
    {
        return $this->fax;
    }

    public function setFax(?string $fax): self
    {
        $this->fax = $fax;

        return $this;
    }

    public function getEmail2(): ?string
    {
        return $this->email2;
    }

    public function setEmail2(?string $email2): self
    {
        $this->email2 = $email2;

        return $this;
    }

    public function getWorkarea(): ?string
    {
        return $this->workarea;
    }

    public function setWorkarea(?string $workarea): self
    {
        $this->workarea = $workarea;

        return $this;
    }

    public function getTitleandtasks(): ?string
    {
        return $this->titleandtasks;
    }

    public function setTitleandtasks(?string $titleandtasks): self
    {
        $this->titleandtasks = $titleandtasks;

        return $this;
    }

    public function getEdulis(): ?string
    {
        return $this->edulis;
    }

    public function setEdulis(?string $edulis): self
    {
        $this->edulis = $edulis;

        return $this;
    }

    public function getEdumaster(): ?string
    {
        return $this->edumaster;
    }

    public function setEdumaster(?string $edumaster): self
    {
        $this->edumaster = $edumaster;

        return $this;
    }

    public function getEdudoc(): ?string
    {
        return $this->edudoc;
    }

    public function setEdudoc(?string $edudoc): self
    {
        $this->edudoc = $edudoc;

        return $this;
    }

    public function getThesismaster(): ?string
    {
        return $this->thesismaster;
    }

    public function setThesismaster(?string $thesismaster): self
    {
        $this->thesismaster = $thesismaster;

        return $this;
    }

    public function getThesisdoc(): ?string
    {
        return $this->thesisdoc;
    }

    public function setThesisdoc(?string $thesisdoc): self
    {
        $this->thesisdoc = $thesisdoc;

        return $this;
    }

    public function getRoomno(): ?string
    {
        return $this->roomno;
    }

    public function setRoomno(?string $roomno): self
    {
        $this->roomno = $roomno;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getNotification(): ?int
    {
        return $this->notification;
    }

    public function setNotification(?int $notification): self
    {
        $this->notification = $notification;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\FollowRepository;
use App\Repository\QuestionsRepository;
use App\Repository\ResearchRepository;
use App\Repository\UserinfoRepository;
use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use phpDocumentor\Reflection\Types\Integer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;


class HomeController extends AbstractController
{
    /**
     * @Route("/", name="firstpage")
     */
    public function firstpage(AuthenticationUtils $authenticationUtils)
    {
        if($authenticationUtils->getLastUsername()){
            return $this->redirectToRoute('home');
        }
        else
        {
            return $this->render('firstpage.html.twig');
        }
    }

    /**
     * @Route("/home", name="home")
     */
    public function index(AuthenticationUtils $authenticationUtils,FollowRepository $followRepository,UserRepository $userRepository)
    {

        $research = array();
        $emm = $this->getDoctrine()->getManager();
        $sqll = 'SELECT * FROM user ORDER BY RAND() DESC LIMIT 4';
        $statementt = $emm->getConnection()->prepare($sqll);
        $statementt->execute();
        $suggestion = $statementt->fetchAll();


        $followidlist = array();

        $user=$this->getUser();
        $userid=$this->getUser()->getID();

        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();
        $followc=$followRepository-> findBy( array('followid' => $userid) ); // TAKIPCI SAYISI
        $followd=$followRepository-> findBy( array('userid' => $userid) ); // TAKIP ETTIGI SAYISI

        for ($i = 0; $i < count($followd); $i++) {
            $followidlist[$i]=$followd[$i]->getFollowid();

            $questionem= $this->getDoctrine()->getManager();
            $sqlconnect = 'SELECT * FROM research WHERE userid = :userid ORDER BY ID';
            $statementqu = $questionem->getConnection()->prepare($sqlconnect);
            $statementqu-> bindValue('userid', $followidlist[$i]);
            $statementqu->execute();
            $research[$i] = $statementqu->fetchAll();

        }

        $em = $this->getDoctrine()->getManager();
        $sql = "SELECT * FROM questions WHERE status='New' and ruid=:ruid ";
        $statement = $em->getConnection()->prepare($sql);
        $statement-> bindValue('ruid', $userid);
        $statement->execute();
        $notification = $statement->fetchAll();

        $em2=$this->getDoctrine()->getManager();
        $sql2="UPDATE user SET notification=:notification WHERE id=:id";
        $statement2=$em2->getConnection()->prepare($sql2);
        $statement2->bindValue('notification', count($notification));
        $statement2->bindValue('id', $userid);
        $statement2->execute();



        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'followc' => count($followc),
            'followd' => count($followd),
            'research' => $research,
            'notification' => count($notification),
            'user' => $user,
            'suggestion' => $suggestion,
            'last_username' => $lastUsername,
            'error' => $error,
        ]);
    }


    /**
     * @Route("/newuser", name="new_user", methods={"GET","POST"})
     */
    public function newuser(Request $request, UserRepository $userRepository): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        $submittedToken = $request->request->get('token');
        if($form->isSubmitted()) {
            if ($this->isCsrfTokenValid('user-form', $submittedToken)) {


                $entityManager = $this->getDoctrine()->getManager();
                $user->setRoles("ROLE_USER");
                $entityManager->persist($user);
                $entityManager->flush();

                return $this->redirectToRoute('app_login');
            }
        }

        return $this->render('home/newuser.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/search/", name="search", methods={"GET","POST"})
     */
    public function search(Request $request):Response
    {
        $search=$request->request->get('search');

        $key='%'. $search.'%';

        $em = $this->getDoctrine()->getManager();
        $sql = "SELECT * FROM user WHERE name like :sea ";
        $statement = $em->getConnection()->prepare($sql);
        $statement-> bindValue('sea', $key);
        $statement->execute();
        $searchuser = $statement->fetchAll();

        $em2 = $this->getDoctrine()->getManager();
        $sql2 = "SELECT * FROM research WHERE title like :rsea ";
        $statement2 = $em2->getConnection()->prepare($sql2);
        $statement2-> bindValue('rsea', $key);
        $statement2->execute();
        $searchre = $statement2->fetchAll();


        return $this->render('home/search.html.twig', [
            'search' => $searchuser,
            'searchre' => $searchre,
        ]);
    }


}

templates/home/_leftbar.html.twig
<div class="col-lg-3 col-md-4 pd-left-none no-pd">
    <div class="main-left-sidebar no-margin">
        <div class="user-data full-width">
            <div class="user-profile">
                <div class="username-dt">
                    <div class="usr-pic">
                        <img src="{{ asset('uploads') }}/{{ app.user.image }}" alt="">
                    </div>
                </div><!--username-dt end-->
                <div class="user-specs">
                    <h3>{{ app.user.name }}</h3>
                    <span>{{ app.user.department }}</span>
                </div>
            </div><!--user-profile end-->
            <ul class="user-fw-status">
                <li>
                    <h4>Takip</h4>
                    <span>{{ followd }}</span>
                </li>
                <li>
                    <h4>Takipçi</h4>
                    <span>{{ followc }}</span>
                </li>
                <!--<li>
                    <a href="/myprofile" title="">Profili Görüntüle</a>
                </li>-->
            </ul>
        </div><!--user-data end-->
        <div class="suggestions full-width">
            <div class="sd-title">
                <h3>Önerilenler</h3>
            </div><!--sd-title end-->
            <div class="suggestions-list">
                {% for rs in suggestion %}
                <div class="suggestion-usd">
                    <a href="/profile/{{ rs.id }}" title="">
                    <img src="{{ asset('uploads') }}/{{ rs.image }}" height="30px" alt="">
                    <div class="sgt-text">
                        <h4>{{ rs.name }}</h4>
                        <span>{{ rs.workarea }}</span>
                    </div>
                    </a>
                </div>
                {% endfor %}
                <div class="view-more">
                    <a href="/profile" title="">Daha Fazla Görüntüle</a>
                </div>
            </div><!--suggestions-list end-->
        </div><!--suggestions end-->
    </div><!--main-left-sidebar end-->
</div>

templates/home/_rightbar.html.twig
<div class="col-lg-3 pd-right-none no-pd">
    <div class="right-sidebar">
        <!--widget-about end<div class="widget widget-about">
            <img src="{{ asset('theme') }}\images\wd-logo.png" alt="">
            <h3>Track Time on Workwise</h3>
            <span>Pay only for the Hours worked</span>
            <div class="sign_link">
                <h3><a href="#" title="">Sign up</a></h3>
                <a href="#" title="">Learn More</a>
            </div>
        </div>--><!--widget-about end-->
        <div class="widget widget-jobs">
            <div class="sd-title">
                <h3>Top Jobs</h3>
                <i class="la la-ellipsis-v"></i>
            </div>
            <div class="jobs-list">
                <div class="job-info">
                    <div class="job-details">
                        <h3>Senior Product Designer</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit..</p>
                    </div>
                    <div class="hr-rate">
                        <span>$25/hr</span>
                    </div>
                </div><!--job-info end-->
                <div class="job-info">
                    <div class="job-details">
                        <h3>Senior UI / UX Designer</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit..</p>
                    </div>
                    <div class="hr-rate">
                        <span>$25/hr</span>
                    </div>
                </div><!--job-info end-->
                <div class="job-info">
                    <div class="job-details">
                        <h3>Junior Seo Designer</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit..</p>
                    </div>
                    <div class="hr-rate">
                        <span>$25/hr</span>
                    </div>
                </div><!--job-info end-->
                <div class="job-info">
                    <div class="job-details">
                        <h3>Senior PHP Designer</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit..</p>
                    </div>
                    <div class="hr-rate">
                        <span>$25/hr</span>
                    </div>
                </div><!--job-info end-->
                <div class="job-info">
                    <div class="job-details">
                        <h3>Senior Developer Designer</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit..</p>
                    </div>
                    <div class="hr-rate">
                        <span>$25/hr</span>
                    </div>
                </div><!--job-info end-->
            </div><!--jobs-list end-->
        </div><!--widget-jobs end-->
        <div class="widget widget-jobs">
            <div class="sd-title">
                <h3>Most Viewed This Week</h3>
                <i class="la la-ellipsis-v"></i>
            </div>
            <div class="jobs-list">
                <div class="job-info">
                    <div class="job-details">
                        <h3>Senior Product Designer</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit..</p>
                    </div>
                    <div class="hr-rate">
                        <span>$25/hr</span>
                    </div>
                </div><!--job-info end-->
                <div class="job-info">
                    <div class="job-details">
                        <h3>Senior UI / UX Designer</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit..</p>
                    </div>
                    <div class="hr-rate">
                        <span>$25/hr</span>
                    </div>
                </div><!--job-info end-->
                <div class="job-info">
                    <div class="job-details">
                        <h3>Junior Seo Designer</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit..</p>
                    </div>
                    <div class="hr-rate">
                        <span>$25/hr</span>
                    </div>
                </div><!--job-info end-->
            </div><!--jobs-list end-->
        </div><!--widget-jobs end-->
        <div class="tags-sec full-width">
            <ul>
                <li><a href="#" title="">Help Center</a></li>
                <li><a href="#" title="">About</a></li>
                <li><a href="#" title="">Privacy Policy</a></li>
                <li><a href="#" title="">Community Guidelines</a></li>
                <li><a href="#" title="">Cookies Policy</a></li>
                <li><a href="#" title="">Career</a></li>
                <li><a href="#" title="">Language</a></li>
                <li><a href="#" title="">Copyright Policy</a></li>
            </ul>
            <div class="cp-sec">
                <img src="{{ asset('theme') }}\images\logo2.png" alt="">
                <p><img src="{{ asset('theme') }}\images\cp.png" alt="">Copyright 2017</p>
            </div>
        </div><!--tags-sec end-->
    </div><!--right-sidebar end-->
</div>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Akademik Portal{% endblock %}

{% block leftbar %}{{  include ('home/_leftbar.html.twig') }} {% endblock %}
{% block content %}{{  include ('home/_content.html.twig') }} {% endblock %}

templates/home/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Search Result{% endblock %}

{% block body %}
    <section class="companies-info">
        <div class="container">
            <div class="company-title">
                <h3>User Result</h3>
            </div><!--company-title end-->
            <div class="companies-list">
                <div class="row">
                    {% for user in search %}
                        {% if(user.id!=app.user.id) %}
                    <div class="col-lg-3 col-md-4 col-sm-6 col-12">
                        <div class="company_profile_info">
                            <div class="company-up-info">
                                <img src="{{ asset('uploads') }}/{{ user.image }}" height="100px" alt="">
                                <h3>{{ user.name }}</h3>
                                <h4>{{ user.workarea }}</h4>
                                <ul>
                                    <li><a href="/profile/{{ user.id }}" title="" class="hire-us">View Profile</a></li>
                                </ul>
                            </div>
                        </div><!--company_profile_info end-->
                    </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div><!--companies-list end-->
            <div class="process-comm">
                <a href="#" title=""><img src="images\process-icon.png" alt=""></a>
            </div>
        </div>
    </section><!--companies-info end-->

    <section class="companies-info">
        <div class="container">
            <div class="company-title">
                <h3>Research Result</h3>
            </div><!--company-title end-->
            <div class="companies-list">
                <div class="row">
                    {% for research in searchre %}
                            <div class="col-lg-12 col-md-4 col-sm-6 col-12">
                                <div class="company_profile_info">
                                    <div class="company-up-info">
                                        <object data="{{ asset('uploads') }}\{{ research.upload }}" type="application/pdf" width="90%" height="400px">
                                            <p>PDF Görüntülenemiyor. Lütfen dosyayı indirerek görüntüleyiniz.<a href="{{ asset('uploads') }}\{{ research.upload }}">İndir</a></p>
                                        </object>
                                        <h3>{{ research.title }}</h3>
                                        <h4>{{ research.abstract }}</h4>
                                        <ul>
                                            <li><a href="/research/{{ research.id }}" title="" class="hire-us">View Research</a></li>
                                            <li>
                                                <form action="{{ path('research_update', {'id': research.id}) }}" method="post">
                                                    <input type="hidden" value="{{ research.view }}" name="view">
                                                    <a title="" class="follow"><input type="submit" style="border: none;
    outline: none;
    background: none;
    cursor: pointer;
    color: white;
    padding: 0;" value="View"></a>
                                                </form></li>
                                            <li><a class="message-us"><i class="la la-eye"></i>Views {{ research.view }}</a></li>
                                        </ul>
                                    </div>
                                </div><!--company_profile_info end-->
                    {% endfor %}
                </div>
            </div><!--companies-list end-->
            <div class="process-comm">
                <a href="#" title=""><img src="images\process-icon.png" alt=""></a>
            </div>
        </div>
    </section><!--companies-info end-->
{% endblock %}