src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $roles;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Location;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $School;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Department;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $website;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $info;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $skills;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fax;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email2;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $workarea;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $titleandtasks;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $edulis;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $edumaster;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $edudoc;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $thesismaster;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $thesisdoc;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $roomno;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $notification;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles= explode(',',$this->roles);
        return array_unique($roles);
    }

    public function setRoles(string $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = password_hash($password,PASSWORD_BCRYPT);

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->Location;
    }

    public function setLocation(?string $Location): self
    {
        $this->Location = $Location;

        return $this;
    }

    public function getSchool(): ?string
    {
        return $this->School;
    }

    public function setSchool(?string $School): self
    {
        $this->School = $School;

        return $this;
    }

    public function getDepartment(): ?string
    {
        return $this->Department;
    }

    public function setDepartment(?string $Department): self
    {
        $this->Department = $Department;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getInfo(): ?string
    {
        return $this->info;
    }

    public function setInfo(?string $info): self
    {
        $this->info = $info;

        return $this;
    }

    public function getSkills(): ?string
    {
        return $this->skills;
    }

    public function setSkills(?string $skills): self
    {
        $this->skills = $skills;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getFax(): ?string
    {
        return $this->fax;
    }

    public function setFax(?string $fax): self
    {
        $this->fax = $fax;

        return $this;
    }

    public function getEmail2(): ?string
    {
        return $this->email2;
    }

    public function setEmail2(?string $email2): self
    {
        $this->email2 = $email2;

        return $this;
    }

    public function getWorkarea(): ?string
    {
        return $this->workarea;
    }

    public function setWorkarea(?string $workarea): self
    {
        $this->workarea = $workarea;

        return $this;
    }

    public function getTitleandtasks(): ?string
    {
        return $this->titleandtasks;
    }

    public function setTitleandtasks(?string $titleandtasks): self
    {
        $this->titleandtasks = $titleandtasks;

        return $this;
    }

    public function getEdulis(): ?string
    {
        return $this->edulis;
    }

    public function setEdulis(?string $edulis): self
    {
        $this->edulis = $edulis;

        return $this;
    }

    public function getEdumaster(): ?string
    {
        return $this->edumaster;
    }

    public function setEdumaster(?string $edumaster): self
    {
        $this->edumaster = $edumaster;

        return $this;
    }

    public function getEdudoc(): ?string
    {
        return $this->edudoc;
    }

    public function setEdudoc(?string $edudoc): self
    {
        $this->edudoc = $edudoc;

        return $this;
    }

    public function getThesismaster(): ?string
    {
        return $this->thesismaster;
    }

    public function setThesismaster(?string $thesismaster): self
    {
        $this->thesismaster = $thesismaster;

        return $this;
    }

    public function getThesisdoc(): ?string
    {
        return $this->thesisdoc;
    }

    public function setThesisdoc(?string $thesisdoc): self
    {
        $this->thesisdoc = $thesisdoc;

        return $this;
    }

    public function getRoomno(): ?string
    {
        return $this->roomno;
    }

    public function setRoomno(?string $roomno): self
    {
        $this->roomno = $roomno;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getNotification(): ?int
    {
        return $this->notification;
    }

    public function setNotification(?int $notification): self
    {
        $this->notification = $notification;

        return $this;
    }
}

src/Form/ResearchType.php
<?php

namespace App\Form;

use App\Entity\Research;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ResearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('keywords')
            ->add('abstract')
            ->add('userid')
            ->add('upload')
            ->add('view')
            ->add('download')
            ->add('username')
            ->add('userlocation')
            ->add('userimage')
            ->add('addtime')
            ->add('recommendname')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Research::class,
            'csrf_protection' => false,
        ]);
    }
}

src/Controller/ResearchController.php
<?php

namespace App\Controller;

use App\Entity\Research;
use App\Form\ResearchType;
use App\Repository\ResearchRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/research")
 */
class ResearchController extends AbstractController
{
    /**
     * @Route("/", name="research_main", methods={"GET"})
     */
    public function main(ResearchRepository $researchRepository): Response
    {
        return $this->render('research/main.html.twig', [
            'researches' => $researchRepository->findAll(),
        ]);
    }

    /**
     * @Route("/index", name="research_index", methods={"GET"})
     */
    public function index(ResearchRepository $researchRepository): Response
    {
        return $this->render('research/index.html.twig', [
            'researches' => $researchRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="research_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $research = new Research();
        $form = $this->createForm(ResearchType::class, $research);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($research);
            $entityManager->flush();
            $rid = $research->getId();

            return $this->render('file/new.html.twig', [
                'rid' => $rid,
            ]);
        }

        return $this->render('research/new.html.twig', [
            'research' => $research,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/new2", name="research_new2", methods={"GET","POST"})
     */
    public function new2(Request $request): Response
    {
        $research = new Research();
        $form = $this->createForm(ResearchType::class, $research);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($research);
            $entityManager->flush();

            return $this->redirectToRoute('home');
        }

        return $this->redirectToRoute('home');
    }


    /**
     * @Route("/{id}", name="research_show", methods={"GET"})
     */
    public function show($id,Research $research): Response
    {
        $questionem= $this->getDoctrine()->getManager();
        $sqlconnect = 'SELECT * FROM questions WHERE rid = :rid and status="Reply" ORDER BY ID';
        $statementqu = $questionem->getConnection()->prepare($sqlconnect);
        $statementqu-> bindValue('rid', $id);
        $statementqu->execute();
        $question = $statementqu->fetchAll();



        return $this->render('research/show.html.twig', [
            'rs' => $research,
            'question' => $question,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="research_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Research $research): Response
    {
        $form = $this->createForm(ResearchType::class, $research);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('research_index', [
                'id' => $research->getId(),
            ]);
        }

        return $this->render('research/edit.html.twig', [
            'research' => $research,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/update", name="research_update", methods={"GET","POST"})
     */
    public function file_update($id, Request $request, Research $research):Response
    {
        $em=$this->getDoctrine()->getManager();
        $sql="UPDATE research SET view=:view WHERE id=:id";
        $statement=$em->getConnection()->prepare($sql);
        $view=$request->request->get('view');
        $statement->bindValue('view', ++$view);
        $statement->bindValue('id', $id);
        $statement->execute();

        return $this->render('research/index.html.twig', [
            'research' => $research,
        ]);
    }

    /**
     * @Route("/{id}", name="research_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Research $research): Response
    {
        if ($this->isCsrfTokenValid('delete'.$research->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($research);
            $entityManager->flush();
        }

        return $this->redirectToRoute('research_index');
    }

}

templates/research/_delete_form.html.twig
<form method="post" action="{{ path('research_delete', {'id': research.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ research.id) }}">
    <button class="btn">Delete</button>
</form>

templates/research/_form.html.twig
<div class="post-project">
    <h3>New Research</h3>
    <div class="post-project-fields">
        <form method="post">
            <div class="row">
                <div class="col-lg-12">
                    <input type="text" name="research[title]" placeholder="Title">
                </div>
                <div class="col-lg-12">
                    <input type="text" name="research[description]" placeholder="Description">
                </div>
                <div class="col-lg-12">
                    <input type="text" name="research[keywords]" placeholder="Keywords">
                </div>
                <div class="col-lg-12">
                    <textarea name="research[abstract]" placeholder="Abstract"></textarea>
                </div>
                <div class="col-lg-6">
                    <input type="hidden" name="research[userid]" value="{{ app.user.id }}" placeholder="User ID">
                    <input type="hidden" name="research[username]" value="{{ app.user.name }}" placeholder="User ID">
                    <input type="hidden" name="research[userlocation]" value="{{ app.user.location }}" placeholder="User ID">
                    <input type="hidden" name="research[userimage]" value="{{ app.user.image }}" placeholder="User ID">
                </div>
                <input type="hidden" name="research[upload]" value="Empty">
                <div class="col-lg-12">
                    <ul>
                        <li><button class="active" type="submit" value="post">Post</button></li>
                        <li><a href="/" title="">Cancel</a></li>
                    </ul>
                </div>
            </div>
        </form>
    </div><!--post-project-fields end-->
    <a href="#" title=""><i class="la la-times-circle-o"></i></a>
</div><!--post-project end-->

templates/research/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Research{% endblock %}

{% block body %}
    <h1>Edit Research</h1>

    {{ include('research/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('research_index') }}">back to list</a>

    {{ include('research/_delete_form.html.twig') }}
{% endblock %}

templates/research/index.html.twig
<html>
<meta http-equiv="refresh" content="0;URL=http://192.168.1.55:8000/uploads/{{ research.upload }}">
</html>

templates/research/main.html.twig
{% extends 'base.html.twig' %}

{% block title %}All Researches{% endblock %}

{% block body %}
    <section class="companies-info">
        <div class="container">
            <div class="company-title">
                <h3>All Researches</h3>
            </div><!--company-title end-->
            <div class="companies-list">
                <div class="row">
                    {% for rs in researches %}

                            <div class="col-lg-12 col-md-4 col-sm-6 col-12">
                                <div class="company_profile_info">
                                    <div class="company-up-info">
                                        <iframe src="{{ asset('uploads') }}\{{ rs.upload }}" frameborder="0" height="400px" width="780px"></iframe>
                                        <h3>{{ rs.title }}</h3>
                                        <h4>{{ rs.abstract }}</h4>
                                        <ul>
                                            <li><a href="/research/{{ rs.id }}" title="" class="hire-us">View Research</a></li>
                                            <li>
                                            <form action="{{ path('research_update', {'id': rs.id}) }}" method="post">
                                                <input type="hidden" value="{{ rs.view }}" name="view">
                                                <a title="" class="follow"><input type="submit" style="border: none;
    outline: none;
    background: none;
    cursor: pointer;
    color: white;
    padding: 0;" value="View"></a>
                                            </form></li>
                                            <li><a class="message-us"><i class="la la-eye"></i>Views {{ rs.view }}</a></li>
                                        </ul>
                                    </div>
                                </div><!--company_profile_info end-->
                            </div>
                    {% endfor %}
                </div>
            </div><!--companies-list end-->
            <div class="process-comm">
                <a href="#" title=""><img src="images\process-icon.png" alt=""></a>
            </div>
        </div>
    </section><!--companies-info end-->
{% endblock %}

templates/research/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Research{% endblock %}

{% block body %}

    {{ include('research/_form.html.twig') }}

{% endblock %}

templates/research/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Research{% endblock %}

{% block body %}
<div class="posts-section">
            <div class="posty">
                <div class="post-bar no-margin">
                    <div class="post_topbar">
                        <div class="usy-dt">
                            <a href="/profile/{{ rs.userid }}" title="">
                                <img src="{{ asset('uploads') }}/{{ rs.userimage }}" alt="" height="40"></a>
                            <div class="usy-name">
                                <h3>{{ rs.username }}</h3>
                                <span><img src="{{ asset('theme') }}\images\clock.png" alt=""></span>
                            </div>
                        </div>
                        <div class="ed-opts">
                            <a href="#" title="" class="ed-opts-open"><i class="la la-ellipsis-v"></i></a>
                            <ul class="ed-options">
                                <li><a href="#" title="">Edit Post</a></li>
                                <li><a href="#" title="">Unsaved</a></li>
                                <li><a href="#" title="">Unbid</a></li>
                                <li><a href="#" title="">Close</a></li>
                                <li><a href="#" title="">Hide</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="epi-sec">
                        <ul class="descp">
                            <li><img src="{{ asset('theme') }}\images\icon9.png" alt=""><span>{{ rs.userlocation }}</span></li>
                        </ul>
                        <ul class="bk-links">
                            <li><a href="#" title=""><i class="la la-bookmark"></i></a></li>
                            <li><a href="#" title=""><i class="la la-envelope"></i></a></li>
                        </ul>
                    </div>
                    <div class="job_descp">
                        <h3>{{ rs.title }}</h3>
                        <ul class="job-dt" style="width: 100%">
                            <li><iframe src="{{ asset('uploads') }}\{{ rs.upload }}" frameborder="0" height="400px" width="780px"></iframe></li>
                        </ul>
                        <p>{{ rs.abstract }}</p>
                    </div>
                    <div class="job-status-bar">
                        <ul class="like-com">
                            <li>
                                <form action="{{ path('research_update', {'id': rs.id}) }}" method="post">
                                    <input type="hidden" value="{{ rs.view }}" name="view">
                                    <a><i class="la la-heart"><input type="submit" value="View"></i></a>
                                </form>
                            </li>
                        </ul>
                        <a><i class="la la-eye"></i>Views {{ rs.view }}</a>
                    </div>
                </div><!--post-bar end-->

                <div class="comment-section">
                    {% for qs in question %}
                    <div class="comment-sec">
                        <ul>
                            <li>
                                <div class="comment-list">
                                    <div class="bg-img">
                                        <img src="{{ asset('uploads') }}\{{ qs.askphoto }}" height="40px" alt="">
                                    </div>
                                    <div class="comment">
                                        <h3>{{ qs.askname }}</h3>
                                        <span><img src="{{ asset('theme') }}\images\clock.png" alt=""> 3 min ago</span>
                                        <p>{{ qs.question }} </p>
                                    </div>
                                </div><!--comment-list end-->
                                <ul>
                                    <li>
                                        <div class="comment-list">
                                            <div class="bg-img">
                                                <img src="{{ asset('uploads') }}\{{ qs.answerphoto }}" height="40px" alt="">
                                            </div>
                                            <div class="comment">
                                                <h3>{{ qs.answername }}</h3>
                                                <span><img src="{{ asset('theme') }}\images\clock.png" alt=""> 3 min ago</span>
                                                <p>{{ qs.answer }} </p>
                                            </div>
                                        </div><!--comment-list end-->
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div><!--comment-sec end-->

                    {% endfor %}
                    <div class="post-comment">
                        <div class="cm_img">
                            <img src="{{ asset('uploads') }}/{{ app.user.image }}" height="40px" alt="">
                        </div>
                        <div class="comment_box">
                            <form action="{{ path('questions_new') }}" method="post">
                                <input type="text" name="questions[question]" placeholder="Ask a question?">
                                <input type="hidden" name="questions[askphoto]" value="{{ app.user.image }}">
                                <input type="hidden" name="questions[askname]" value="{{ app.user.name }}" >
                                <input type="hidden" name="questions[status]" value="New" >
                                <input type="hidden" name="questions[rid]" value="{{ rs.id }}">
                                <input type="hidden" name="questions[ruid]" value="{{ rs.userid }}">
                                <input type="hidden" name="questions[rname]" value="{{ rs.title }}">
                                <button type="submit">Send</button>
                            </form>
                        </div>
                    </div><!--post-comment end-->
                </div><!--comment-section end-->
            </div><!--posty end-->
            <div class="process-comm">
            </div><!--process-comm end-->
</div>
{% endblock %}